import type { WebsiteOpportunityType, WebsiteServiceId } from "./types";

export const OPPORTUNITY_ENGINE_VERSION = "1.0.0" as const;

export const WEBSITE_OPPORTUNITY_TYPES: readonly WebsiteOpportunityType[] = [
  "WEBSITE_REDESIGN",
  "TECHNICAL_REMEDIATION",
  "PERFORMANCE_OPTIMIZATION",
  "MOBILE_EXPERIENCE",
  "ACCESSIBILITY_REMEDIATION",
  "CONVERSION_UX_IMPROVEMENT",
  "CONTENT_IMPROVEMENT",
  "SEO_IMPROVEMENT",
  "SECURITY_CONFIGURATION",
] as const;

export const WEBSITE_SERVICE_BY_OPPORTUNITY: Readonly<
  Record<WebsiteOpportunityType, WebsiteServiceId>
> = {
  WEBSITE_REDESIGN: "WEBSITE_REDESIGN",
  TECHNICAL_REMEDIATION: "TECHNICAL_WEBSITE_REMEDIATION",
  PERFORMANCE_OPTIMIZATION: "PERFORMANCE_OPTIMIZATION",
  MOBILE_EXPERIENCE: "MOBILE_OPTIMIZATION",
  ACCESSIBILITY_REMEDIATION: "ACCESSIBILITY_REMEDIATION",
  CONVERSION_UX_IMPROVEMENT: "CONVERSION_UX_OPTIMIZATION",
  CONTENT_IMPROVEMENT: "CONTENT_OPTIMIZATION",
  SEO_IMPROVEMENT: "SEO_OPTIMIZATION",
  SECURITY_CONFIGURATION: "WEBSITE_SECURITY_CONFIGURATION",
} as const;

export const PROHIBITED_WEBSITE_ONLY_SERVICE_IDS = [
  "INTERNAL_TOOL",
  "CRM",
  "CUSTOMER_PORTAL",
  "AI_AUTOMATION",
  "MOBILE_APP",
  "BOOKING_SYSTEM",
  "ECOMMERCE",
] as const;
